version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ivnio/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media
  frontend:
    image: ivnio/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: ivnio/kittygram_gateway:latest
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/var/www/media